-- Yemek veritabanının İngilizce isimleri.
--
-- Neden: uygulama dili İngilizce yapıldığında arayüz çevriliyordu ama yemek
-- adları Türkçe kalıyordu. Bu migration foods.name_en'i doldurur ve
-- search_foods'u İngilizce adı da arayacak şekilde günceller.
--
-- Adlandırma kuralı:
--   * Uluslararası karşılığı olan yiyecek → doğrudan İngilizce (Mercimek çorbası → Lentil Soup)
--   * Türk mutfağına özgü, karşılığı olmayan yemek → özgün ad + kısa açıklama
--     (Karnıyarık → "Karnıyarık (Stuffed Eggplant with Minced Meat)")
--   * Markalı ürün → marka/ürün özel adı korunur, betimleyici kısım çevrilir
--     (Ülker Kakaolu Bisküvi → "Ülker Cocoa Biscuits")
--
-- Eşleştirme tr_fold ile yapılır: büyük/küçük harf ve Türkçe karakter farkları
-- (Saklıköy/Sakliköy, Hindi füme/Hindi Füme) tek anahtarla yakalanır. Barkod
-- taramasından gelen bozuk name_en değerleri de bu yolla düzeltilir.

update public.foods f
set name_en = m.en
from (
  select key as tr, value as en
  from jsonb_each_text($json${
  "%1,5 yarım yağlı Süt": "Semi-Skimmed Milk 1.5%",
  "3'ü 1 arada hazır kahve": "3-in-1 Instant Coffee",
  "4x4 Karamelli ve Fıstıklı Nuga Bar": "4x4 Caramel & Peanut Nougat Bar",
  "Acı sos (sriracha)": "Hot Sauce (Sriracha)",
  "Açma (sade)": "Açma (Turkish Soft Bagel, Plain)",
  "Activia": "Activia Yogurt",
  "Adana kebap": "Adana Kebab",
  "Agave şurubu": "Agave Syrup",
  "Akçaağaç şurubu": "Maple Syrup",
  "Albeni": "Albeni Caramel Chocolate Bar",
  "Albeni Viva": "Albeni Viva Chocolate Bar",
  "Altınbaşak Grissini": "Altınbaşak Grissini Breadsticks",
  "Altınbaşak Light": "Altınbaşak Light Crackers",
  "Altınbaşak tahıl cipsi": "Altınbaşak Grain Chips",
  "Altınkılıç Kefir Sade": "Altınkılıç Plain Kefir",
  "Americano": "Americano",
  "Aromalı Bitkisel Yağlı Sütlü Buz": "Flavoured Milk Ice Bar",
  "Assu": "Assu Mineral Water",
  "ASSU Doğal Mineralli Su": "ASSU Natural Mineral Water",
  "Avşar Karadut ve Meyveli": "Avşar Black Mulberry & Fruit Drink",
  "Ay Çekirdeği": "Sunflower Seeds",
  "Ayçiçek yağı": "Sunflower Oil",
  "Ayran": "Ayran (Yogurt Drink)",
  "Ayva": "Quince",
  "Ayva tatlısı": "Quince Dessert",
  "Badem (kavrulmuş)": "Almonds (Roasted)",
  "Badem ezmesi": "Almond Butter",
  "Badem Su": "Almond Milk",
  "Baget ekmek": "Baguette",
  "Ballı Granola": "Honey Granola",
  "Ballı Granola Çikolata . Fındık": "Honey Granola with Chocolate & Hazelnut",
  "Banada Fındık Kreması": "Banada Hazelnut Cocoa Spread",
  "Bar Kek": "Bar Cake",
  "Barbekü sos": "Barbecue Sauce",
  "Barbunya (haşlanmış)": "Borlotti Beans (Boiled)",
  "Barbunya pilaki": "Borlotti Bean Pilaki (Olive Oil Stew)",
  "Basmati pirinç (çiğ)": "Basmati Rice (Raw)",
  "Basmati pirinç (haşlanmış)": "Basmati Rice (Boiled)",
  "BCAA (toz, aromalı)": "BCAA (Powder, Flavoured)",
  "Becel Tereyağı Keyfi Bitkisel Margarin 57% yağlı": "Becel Butter Taste Plant Margarine 57% Fat",
  "Beyaz lahana": "White Cabbage",
  "Beyaz Peynir": "White Cheese (Beyaz Peynir)",
  "Bezelye (pişmiş)": "Green Peas (Cooked)",
  "Biber dolması (etli)": "Stuffed Peppers with Minced Meat",
  "Biberli Sos": "Pepper Sauce",
  "Big Babol Meyve Aromalı Sakız": "Big Babol Fruit Flavoured Gum",
  "Big Mac": "Big Mac",
  "Birşah Kefir": "Birşah Kefir",
  "Bitter Çikolata": "Dark Chocolate",
  "Böğürtlen": "Blackberries",
  "Börülce (haşlanmış)": "Black-Eyed Peas (Boiled)",
  "Browni": "Brownie",
  "Brüksel lahanası": "Brussels Sprouts",
  "Buğday unu": "Wheat Flour",
  "Bulgur (pişmiş)": "Bulgur (Cooked)",
  "Bulgur pilavı": "Bulgur Pilaf",
  "buono": "Buono",
  "Burcak": "Burçak Biscuits",
  "Buzlu Çay": "Iced Tea",
  "Buzlu Çay Limon": "Iced Tea Lemon",
  "Cacık": "Cacık (Yogurt & Cucumber Dip)",
  "Cafe Art": "Cafe Art Coffee Drink",
  "Caffè Latte": "Caffè Latte",
  "Caffe mocha": "Caffè Mocha",
  "Calve Ranch Sos": "Calvé Ranch Sauce",
  "Cappy Kiraz": "Cappy Cherry Juice",
  "Çarliston biber": "Charleston Pepper (Long Green Pepper)",
  "çatapat": "Çatapat Ice Cream",
  "Çavdar ekmeği": "Rye Bread",
  "Cevizli baklava": "Walnut Baklava",
  "Cheerios": "Cheerios",
  "Chia tohumu": "Chia Seeds",
  "Chicken Royale": "Chicken Royale",
  "Chokella": "Chokella Cocoa Hazelnut Spread",
  "Çift Kavrulmuş Karışık Kuruyemiş": "Double Roasted Mixed Nuts",
  "Çiğ Köfte": "Çiğ Köfte (Spiced Bulgur Tartare)",
  "Çiğ köfte (etsiz)": "Çiğ Köfte (Meatless)",
  "Çiğ Sebze Sosu": "Raw Vegetable Sauce",
  "Çiğ Tahıllı Kraker": "Whole Grain Crackers",
  "Çikolata %60 Bitter Karadutlu": "60% Dark Chocolate with Black Mulberry",
  "Cikolata %80 Bitter": "80% Dark Chocolate",
  "Çikolata 60% bitter": "60% Dark Chocolate",
  "Cikolata Kaplamah Pismanige": "Chocolate Coated Pişmaniye",
  "Çikolatalı Hindistan Cevizli Puding Toz Karışımı": "Chocolate Coconut Pudding Mix",
  "Çilekli Gofret": "Strawberry Wafer",
  "Cin": "Cin Biscuits",
  "Cin cilek soslu biskuvi": "Cin Strawberry Filled Biscuits",
  "Çipura (çiğ)": "Sea Bream (Raw)",
  "Çizi": "Çizi Cheese Crackers",
  "Çizi viç": "Çizi Viç Sandwich Crackers",
  "Çıtır Tavuk": "Crispy Fried Chicken",
  "Çoban salatası (zeytinyağlı)": "Shepherd's Salad (with Olive Oil)",
  "Coca 900ml": "Coca-Cola 900 ml",
  "Coca cream": "Coca Cream Wafer",
  "Coco pops": "Coco Pops",
  "Çokodamlalı pasta bisküvi": "Chocolate Chip Cookies",
  "Çokokrem": "Çokokrem Cocoa Hazelnut Spread",
  "Çokonat": "Çokonat Chocolate Wafer Bar",
  "Crax Baharatlı Çubuk": "Crax Spicy Sticks",
  "Cubuk craker": "Stick Crackers",
  "Çubuk Kraker": "Stick Crackers",
  "Damak gece": "Damak Dark Pistachio Chocolate",
  "Dana antrikot (çiğ)": "Beef Ribeye (Raw)",
  "Dana antrikot (ızgara)": "Beef Ribeye (Grilled)",
  "Dana biftek (ızgara)": "Beef Steak (Grilled)",
  "Dana kıyma (%20 yağlı, çiğ)": "Ground Beef (20% Fat, Raw)",
  "Dana kuşbaşı (çiğ)": "Beef Cubes (Raw)",
  "Dana Macar Salam": "Beef Hungarian Salami",
  "Dana pastirma": "Beef Pastirma (Cured Beef)",
  "Dankek Bites": "Dankek Bites",
  "Daphne Puding Muzlu": "Daphne Banana Pudding",
  "Dereotu": "Dill",
  "Dido": "Dido Chocolate Wafer",
  "Dido Trio": "Dido Trio Chocolate Wafer",
  "Dil peyniri": "String Cheese (Dil Peyniri)",
  "Dilimli Burger Peyniri": "Sliced Burger Cheese",
  "Dilimli Tost Peyniri": "Sliced Sandwich Cheese",
  "Doğal Kaynak Suyu": "Natural Spring Water",
  "Doğal Salamura Yağlı Siyah Zeytin": "Natural Brined Black Olives",
  "Doğal Siyah Zeytin": "Natural Black Olives",
  "Domates çorbası": "Tomato Soup",
  "Domates Salçasi": "Tomato Paste",
  "Doritos Taco": "Doritos Taco",
  "Dost ayran": "Dost Ayran (Yogurt Drink)",
  "Dost yoğurt": "Dost Yogurt",
  "Dr. Oetker Çırpılmış Krema": "Dr. Oetker Whipped Cream",
  "Dr. Oetker Kakao": "Dr. Oetker Cocoa Powder",
  "Dürüm Çiğ Köfte": "Çiğ Köfte Wrap",
  "Eker Ayran": "Eker Ayran (Yogurt Drink)",
  "Ekşi İp Şeker": "Sour Candy Strings",
  "EKŞİ MAYALI ZEYTİNLİ KEKİKLİ BAGET": "Sourdough Baguette with Olives & Oregano",
  "Ekstra Fındıklı Gofret": "Extra Hazelnut Wafer",
  "Elmacik": "Elmacık",
  "Enerji içeceği": "Energy Drink",
  "Enerji içeceği (şekersiz)": "Energy Drink (Sugar-Free)",
  "Erik": "Plum",
  "Erikli": "Erikli Spring Water",
  "Erişte (çiğ)": "Turkish Egg Noodles (Raw)",
  "Espresso": "Espresso",
  "Et browni gold": "Eti Brownie Gold",
  "Et döner": "Beef Döner",
  "Et sote": "Beef Sauté",
  "Eti Browni Gold": "Eti Brownie Gold",
  "Eti Cin": "Eti Cin Biscuits",
  "Eti Finger Bisküvi": "Eti Finger Biscuits",
  "ETI FORM": "Eti Form Bran Biscuits",
  "Eti Karam Bitter": "Eti Karam Dark Chocolate",
  "Eti lifalif müsli 250 k meyveli": "Eti Lifalif Fruit Muesli 250 g",
  "Eti Pop kek Muzlu": "Eti Popkek Banana Cake",
  "Eti. sütlü çikolata": "Eti Milk Chocolate",
  "Etli güveç": "Meat Casserole (Güveç)",
  "Ezme salata": "Ezme (Spicy Tomato Salad)",
  "Ezogelin cabuk corba": "Ezogelin Instant Soup",
  "Ezogelin çorbası": "Ezogelin Soup (Red Lentil & Bulgur)",
  "Falim Karpuz Sakız": "Falim Watermelon Gum",
  "Fava": "Fava (Broad Bean Purée)",
  "Fesleğen (taze)": "Basil (Fresh)",
  "Filtre kahve (sade)": "Filter Coffee (Black)",
  "FINDIK PARÇACIKLI KAKAOLU KREMA": "Cocoa Spread with Hazelnut Pieces",
  "Fındık (çiğ)": "Hazelnuts (Raw)",
  "Fındıklı Kakaolu Krema": "Hazelnut Cocoa Spread",
  "Fıstık Ezmesi": "Peanut Butter",
  "Fıstık ezmesi (%100 doğal)": "Peanut Butter (100% Natural)",
  "Flat White (tam yağlı süt)": "Flat White (Whole Milk)",
  "Fromage frais Labne": "Labneh Cream Cheese",
  "Fuze Şeftali Buzlu Çay 330ML": "Fuse Tea Peach Iced Tea 330 ml",
  "Gikolatati": "Chocolate Snack",
  "Glutensiz makarna (çiğ)": "Gluten-Free Pasta (Raw)",
  "Gofrik": "Gofrik Wafer",
  "Gözleme (peynirli)": "Gözleme (Turkish Flatbread with Cheese)",
  "Greyfurt": "Grapefruit",
  "Güllaç": "Güllaç (Rosewater Milk Dessert)",
  "Hafif Çiğ Sebze Sosu": "Light Raw Vegetable Sauce",
  "Halley": "Halley Marshmallow Sandwich Biscuit",
  "Hanımeller": "Hanımeller Butter Biscuits",
  "Haribo Jöleli Şekerler": "Haribo Gummy Candies",
  "Haydari": "Haydari (Strained Yogurt Dip)",
  "Hazir noodle": "Instant Noodles",
  "Hazır Noodle": "Instant Noodles",
  "Heinz Domates Ketçabı": "Heinz Tomato Ketchup",
  "Heinz Sarımsaklı Mayonez": "Heinz Garlic Mayonnaise",
  "Heınz": "Heinz Sauce",
  "Hindi füme": "Smoked Turkey",
  "Hindi kıyma (çiğ)": "Ground Turkey (Raw)",
  "Hindistan cevizi sütü (içecek)": "Coconut Milk Drink",
  "Hindistan cevizi yağı": "Coconut Oil",
  "Hünkar beğendi": "Hünkâr Beğendi (Lamb Stew on Eggplant Purée)",
  "Hurma": "Dates",
  "İç pilav": "İç Pilav (Rice Pilaf with Currants & Pine Nuts)",
  "Içim fit çilek": "İçim Fit Strawberry Milk",
  "İçim Fit Kakaolu": "İçim Fit Cocoa Milk",
  "İçim süt 1 litre laktozsuz": "İçim Lactose-Free Milk 1 L",
  "İçim süzme peynir 250": "İçim Cottage Cheese 250 g",
  "İçli köfte": "İçli Köfte (Stuffed Bulgur Croquettes)",
  "İkram": "İkram Cocoa Cream Biscuits",
  "İkram Gold Siyah Zeytin 800G": "İkram Gold Black Olives 800 g",
  "İmam bayıldı": "İmam Bayıldı (Stuffed Eggplant in Olive Oil)",
  "İncir (taze)": "Figs (Fresh)",
  "Indomie Acı Baharatlı": "Indomie Hot & Spicy Noodles",
  "İşkembe çorbası": "Tripe Soup",
  "İskender kebap": "İskender Kebab",
  "Ispanaklı börek": "Spinach Börek (Savoury Pastry)",
  "Izgara köfte": "Grilled Meatballs",
  "İzmir köfte": "İzmir Köfte (Meatballs in Tomato Sauce)",
  "İzole whey protein tozu": "Whey Protein Isolate Powder",
  "Kabak çekirdeği (kavrulmuş)": "Pumpkin Seeds (Roasted)",
  "Kabak dolması (etli)": "Stuffed Zucchini with Minced Meat",
  "Kabak tatlısı": "Candied Pumpkin Dessert",
  "Kadınbudu köfte": "Kadınbudu Köfte (Meat & Rice Croquettes)",
  "Kafeinsiz Türk Kahvesi": "Decaf Turkish Coffee",
  "Kahvaltilik sos": "Breakfast Spread",
  "Kakaolu Cappuccino": "Cocoa Cappuccino",
  "Kakaolu findik cremali": "Cocoa Hazelnut Spread",
  "Kakaolu Fındık Kreması": "Cocoa Hazelnut Spread",
  "Kakaolu Tahıl Gevreği": "Cocoa Cereal",
  "Kalamar (çiğ)": "Squid (Raw)",
  "Kapya biber": "Kapia Red Pepper",
  "Karabuğday (greçka, çiğ)": "Buckwheat (Raw)",
  "Karabuğday (haşlanmış)": "Buckwheat (Boiled)",
  "Karalahana": "Collard Greens (Black Cabbage)",
  "Karam %54 Kakaolu Bitter Çikolata": "Karam 54% Dark Chocolate",
  "Karides (haşlanmış)": "Shrimp (Boiled)",
  "Karnabahar (çiğ)": "Cauliflower (Raw)",
  "Karnıyarık": "Karnıyarık (Stuffed Eggplant with Minced Meat)",
  "Kaşarlı pide": "Pide with Kashar Cheese",
  "Kaşarlı tost": "Grilled Cheese Toast",
  "Kaymak": "Kaymak (Clotted Cream)",
  "Kaymaklı Yoğurt": "Cream-Top Yogurt",
  "Kazein protein tozu": "Casein Protein Powder",
  "KEFIR CILEK ICIM": "İçim Strawberry Kefir",
  "Kefirix Probiyotik Orman Meyveli": "Kefirix Probiotic Forest Fruits",
  "kek": "Cake",
  "Kellogg's® Granola Beyaz Çikolata Parçacıklı ve Antep Fıstıklı (300 g)": "Kellogg's Granola with White Chocolate & Pistachio (300 g)",
  "Kellogs granola klasik 340": "Kellogg's Granola Classic 340 g",
  "Kerem taze sürülebilir peynir": "Kerem Fresh Spreadable Cheese",
  "Kereviz (kök)": "Celeriac (Celery Root)",
  "Keşkek": "Keşkek (Wheat & Meat Porridge)",
  "Ketçap": "Ketchup",
  "Keten tohumu": "Flaxseed",
  "Keyfe Türk Kahvesi": "Keyfe Turkish Coffee",
  "Kinoa (çiğ)": "Quinoa (Raw)",
  "Kinoa (haşlanmış)": "Quinoa (Boiled)",
  "Kivi": "Kiwi",
  "Kırmızı lahana": "Red Cabbage",
  "Kısır": "Kısır (Bulgur Salad)",
  "Kıymalı ıspanak": "Spinach with Minced Meat",
  "Kıymalı pide": "Pide with Minced Meat",
  "Kızarmış yer fıstığı": "Roasted Peanuts",
  "Klasik": "Lay's Classic Potato Chips",
  "Köftelik bulgur (çiğ)": "Fine Bulgur (Raw)",
  "Kokoreç": "Kokoreç (Grilled Lamb Intestines)",
  "Kola (zero)": "Cola (Zero)",
  "Kolajen (toz)": "Collagen (Powder)",
  "Komagene Ayran": "Komagene Ayran (Yogurt Drink)",
  "kornişon turşusu": "Gherkin Pickles",
  "Kraliyet Kuruyemiş Karışımı": "Royal Mixed Nuts",
  "Kreatin monohidrat": "Creatine Monohydrate",
  "Krem peynir": "Cream Cheese",
  "Kremalı Sütlü Çikolata": "Creamy Milk Chocolate",
  "Kuark (sade)": "Quark (Plain)",
  "Kumpir (karışık)": "Kumpir (Loaded Baked Potato)",
  "Künefe": "Künefe (Cheese & Shredded Pastry Dessert)",
  "Kuru fasulye (etli)": "White Bean Stew with Meat",
  "Kuru incir": "Dried Figs",
  "Kuru köfte": "Kuru Köfte (Pan-Fried Meatballs)",
  "Kuşkonmaz": "Asparagus",
  "Kuymak (mıhlama)": "Kuymak (Cheese & Cornmeal Fondue)",
  "Labne": "Labneh Cream Cheese",
  "Lahana sarma (etli)": "Stuffed Cabbage Rolls with Meat",
  "Lahana Sarma 400 GR": "Stuffed Cabbage Rolls 400 g",
  "Lahmacun": "Lahmacun (Turkish Flatbread with Minced Meat)",
  "Latte": "Latte",
  "Laviva": "Laviva Chocolate Bar",
  "Lay's Fırından Yoğurt Mevsim Yeşillikleri": "Lay's Oven Baked Yogurt & Herbs",
  "Lays Klasik Mega 193gr": "Lay's Classic Potato Chips 193 g",
  "Lifalif  yulaf ezmesi": "Lifalif Rolled Oats",
  "Lifalif Müsli Kuru Meyveli ve Fındıklı": "Lifalif Muesli with Dried Fruit & Hazelnut",
  "Lifalif Yulaf Ezmesi": "Lifalif Rolled Oats",
  "Light Ton balığı": "Light Canned Tuna",
  "Limonata": "Lemonade",
  "Limonlu Soda": "Lemon Sparkling Water",
  "Lipton Buzlu Çay (Şeftali)": "Lipton Iced Tea (Peach)",
  "Lokma tatlısı": "Lokma (Syrup-Soaked Fried Dough)",
  "Lor peyniri (yağsız)": "Curd Cheese (Fat-Free)",
  "Luppo choco": "Luppo Choco Cake Bar",
  "Makarna (çiğ)": "Pasta (Raw)",
  "Mantı (yoğurtlu)": "Mantı (Turkish Dumplings with Yogurt)",
  "Maydanoz": "Parsley",
  "Mayonez": "Mayonnaise",
  "Mayonez (light)": "Mayonnaise (Light)",
  "Menemen": "Menemen (Turkish Eggs with Tomato & Pepper)",
  "Mercimek (pişmiş)": "Lentils (Cooked)",
  "Mercimek çorbası": "Lentil Soup",
  "Metro": "Metro Chocolate Bar",
  "Meyve nektarı": "Fruit Nectar",
  "Meyve suyu (%100 portakal)": "Fruit Juice (100% Orange)",
  "Meyveli Sos": "Fruit Sauce",
  "Meyveli yoğurt": "Fruit Yogurt",
  "Mezgit (çiğ)": "Whiting (Raw)",
  "Midye dolma": "Stuffed Mussels",
  "Milka MMMAX Oreo": "Milka MMMAX Oreo",
  "Milka oreo choco": "Milka Oreo Choco",
  "Mini tortilla": "Mini Tortilla",
  "Mis puding çilekli": "Mis Strawberry Pudding",
  "Mısır (haşlanmış)": "Corn (Boiled)",
  "Mısır Gevreği": "Corn Flakes",
  "Mısır patlağı (yağsız)": "Popcorn (Air-Popped)",
  "Mood": "Biscolata Mood",
  "Mücver (kabak)": "Mücver (Zucchini Fritters)",
  "Nacho": "Doritos Nacho Cheese",
  "Nane (taze)": "Mint (Fresh)",
  "Nar Ekşisi": "Pomegranate Molasses",
  "Nescafe": "Nescafé Instant Coffee",
  "Nescafe express 250 milim karamel": "Nescafé Xpress Caramel 250 ml",
  "Nesquik Tahıl Gevreği": "Nesquik Cereal",
  "nestle": "Nestlé Chocolate",
  "Nestle Damak inci": "Nestlé Damak İnci Pistachio Chocolate",
  "Nitrotech, iso whey": "Nitro-Tech Whey Isolate",
  "no:1": "Torku No:1 Chocolate Bar",
  "no:1 more": "Torku No:1 More Chocolate Bar",
  "Nohut (çiğ)": "Chickpeas (Raw)",
  "Nohut yemeği (etli)": "Chickpea Stew with Meat",
  "Noodle": "Instant Noodles",
  "Noodles": "Instant Noodles",
  "Olgun İncir Reçeli": "Ripe Fig Jam",
  "Organik Nar Suyu": "Organic Pomegranate Juice",
  "Örgü peyniri": "Braided Cheese (Örgü Peyniri)",
  "Original": "Wasa Original Crispbread",
  "Originals Patates Cipsi": "Ruffles Original Potato Chips",
  "Orman kebabı": "Orman Kebabı (Forest Kebab Stew)",
  "Patates (çiğ)": "Potato (Raw)",
  "Patates (fırın)": "Potato (Baked)",
  "Patates kızartması": "French Fries",
  "Patates Kızartması (orta)": "French Fries (Medium)",
  "Patatesli börek": "Potato Börek (Savoury Pastry)",
  "Patito Yoğurt ve Mevsim Çeşnili": "Patito Yogurt & Herb Snack",
  "Patlıcan musakka": "Eggplant Moussaka",
  "Pazı": "Chard",
  "Pekmez (üzüm)": "Grape Molasses (Pekmez)",
  "Penne rigate": "Penne Rigate",
  "Pepsi Max Ahududu": "Pepsi Max Raspberry",
  "Pepsi zero sugar": "Pepsi Zero Sugar",
  "Performance": "Performance",
  "Pesto sos": "Pesto Sauce",
  "Peynirli poğaça": "Cheese Poğaça (Savoury Bun)",
  "Pirinç (pişmiş)": "Rice (Cooked)",
  "Pirinç patlağı (sade)": "Puffed Rice (Plain)",
  "Pişi": "Pişi (Fried Dough)",
  "Pismaniye": "Pişmaniye (Turkish Floss Halva)",
  "Pita Sosu": "Pita Sauce",
  "Piyaz": "Piyaz (White Bean Salad)",
  "Pınar hindi salam 75 aç bitir": "Pınar Turkey Salami 75 g",
  "Pınar Kido süt 180 çilek": "Pınar Kido Strawberry Milk 180 ml",
  "Pınar Laktozsuz Süt İçeceği": "Pınar Lactose-Free Milk Drink",
  "Pınar Protein Kakaolu Süt": "Pınar Protein Cocoa Milk",
  "Pınar Süt": "Pınar Milk",
  "Pınar süt 1 litre %1 yağlı": "Pınar Milk 1% Fat 1 L",
  "Pırasa": "Leek",
  "Pop-kek Çikolatalı": "Popkek Chocolate Cake",
  "Portakal Suyu": "Orange Juice",
  "Premium Ekmek": "Premium Bread",
  "Proteinli Kahveli Süt": "Protein Coffee Milk",
  "Pure Life": "Nestlé Pure Life Water",
  "Ramazan pidesi": "Ramadan Pide (Flatbread)",
  "Revani": "Revani (Semolina Syrup Cake)",
  "Rize Çayı": "Rize Black Tea",
  "Roka": "Arugula",
  "Rulokat 9kat tat": "Rulokat Wafer Roll",
  "Sahanda yumurta (tereyağlı)": "Fried Eggs (in Butter)",
  "Saklıköy": "Saklıköy Biscuits",
  "Sandviç ekmeği": "Sandwich Bread",
  "SARELLE": "Sarelle Cocoa Hazelnut Spread",
  "Schogetten Yulaf Bisküvili Sütlü Çikolata": "Schogetten Milk Chocolate with Oat Biscuit",
  "Schweppes 1 lt mandalina": "Schweppes Tangerine 1 L",
  "Şeftali Nektarı": "Peach Nectar",
  "Şeftali Suyu": "Peach Juice",
  "Şehriye (çiğ)": "Vermicelli (Raw)",
  "Şehriye çorbası": "Vermicelli Soup",
  "şekerli fındık ezmesi": "Sweetened Hazelnut Butter",
  "Şekerpare": "Şekerpare (Syrup-Soaked Semolina Cookies)",
  "Şekersiz Yulaf Sütü": "Unsweetened Oat Milk",
  "Sigara böreği": "Sigara Böreği (Cheese-Filled Fried Rolls)",
  "Simbat Kızartılmış Kaju Fıstığı": "Simbat Roasted Cashews",
  "Sirma Eynazli": "Sırma Spring Water",
  "Siyez ekmeği": "Einkorn Bread",
  "Sırma Doğal Maden Suyu": "Sırma Natural Mineral Water",
  "Skippy": "Skippy Peanut Butter",
  "Smoothie": "Smoothie",
  "Somon (çiğ)": "Salmon (Raw)",
  "Sonbahar Yaprağı Bisküvi": "Autumn Leaf Biscuits",
  "Soya fasulyesi (edamame)": "Soybeans (Edamame)",
  "Soya Soslu Hazır Noodle": "Instant Noodles with Soy Sauce",
  "Soya sütü": "Soy Milk",
  "Special K Yulaf ve Bal Gevreği": "Special K Oats & Honey Cereal",
  "Sprite": "Sprite",
  "Stevia (toz tatlandırıcı)": "Stevia (Powder Sweetener)",
  "Sticks": "Eti Sticks",
  "Su böreği (peynirli)": "Su Böreği (Layered Pastry with Cheese)",
  "Sucuklu Pizza": "Sujuk Pizza",
  "Susamlı Wasa Kraker": "Wasa Sesame Crispbread",
  "Süt": "Milk",
  "Süt (yağsız)": "Milk (Skimmed)",
  "Süt Mısır": "Sweet Corn",
  "Sütaş kaşar 400": "Sütaş Kashar Cheese 400 g",
  "Sütaş labne 400": "Sütaş Labneh 400 g",
  "Sütlü Salep": "Salep with Milk",
  "Süzme Peynir": "Cottage Cheese",
  "Süzme Yoğurt": "Strained Yogurt",
  "Tadelle": "Tadelle Hazelnut Chocolate Bar",
  "Tadım İşlenmiş Yer Fıstığı": "Tadım Roasted Peanuts",
  "Tam buğday makarna (çiğ)": "Whole Wheat Pasta (Raw)",
  "Tam buğday makarna (haşlanmış)": "Whole Wheat Pasta (Boiled)",
  "Tam Tahıllı Pirinç": "Whole Grain Rice",
  "Tam yağlı süt": "Whole Milk",
  "Tam Yağlı Taze Eritme Peyniri": "Full-Fat Processed Cheese",
  "Tantuni (dürüm)": "Tantuni (Spiced Beef Wrap)",
  "Tarçınlı Zencefilli Kurabiye": "Cinnamon Ginger Cookies",
  "Tarhana çorbası": "Tarhana Soup",
  "Tas kebabı": "Tas Kebabı (Braised Beef Stew)",
  "tatli biber salçasi": "Mild Pepper Paste",
  "Tatlı mısır (konserve)": "Sweet Corn (Canned)",
  "Tatlı patates (haşlanmış)": "Sweet Potato (Boiled)",
  "Tavuk but (pişmiş)": "Chicken Thigh (Cooked)",
  "Tavuk döner": "Chicken Döner",
  "Tavuk göğsü (çiğ)": "Chicken Breast (Raw)",
  "Tavuk kıyması (çiğ)": "Ground Chicken (Raw)",
  "Tavuk şiş (ızgara)": "Chicken Shish (Grilled)",
  "Tavuk sote": "Chicken Sauté",
  "Tavuk Suyu Bulyon": "Chicken Bouillon",
  "Tavuk suyu çorbası": "Chicken Soup",
  "Taze fasulye (pişmiş)": "Green Beans (Cooked)",
  "Taze soğan": "Spring Onion",
  "Tazej": "Tazej",
  "Terbiyeli köfte": "Meatballs in Egg-Lemon Sauce",
  "Teremyağ": "Teremyağ Margarine",
  "Tereyağlı Bisküvi": "Butter Biscuits",
  "Tereyağlı pirinç pilavı": "Rice Pilaf with Butter",
  "Ton balık konservesi": "Canned Tuna",
  "Tortilla": "Tortilla",
  "Tortilla (tam buğday)": "Tortilla (Whole Wheat)",
  "Tost ekmeği": "Sandwich Loaf Bread",
  "Tost iki ekmek arası lezzet molası": "Uno Toast Bread",
  "Trabzon hurması": "Persimmon",
  "Tulumba tatlısı": "Tulumba (Syrup-Soaked Fried Dessert)",
  "Türlü (etli)": "Türlü (Mixed Vegetable Stew with Meat)",
  "Tutku": "Tutku Chocolate Biscuits",
  "Tuzlu Çubuk Bisküvi": "Salted Stick Crackers",
  "Ülker Bol Sütlü Kare Çikolata": "Ülker Extra Milk Chocolate Squares",
  "Ülker Çokokrem": "Ülker Çokokrem Cocoa Hazelnut Spread",
  "Ülker Ekstra Bitter Çikolatalı Gofret": "Ülker Extra Dark Chocolate Wafer",
  "Ülker Fıstıklı Beyaz Çikolata": "Ülker White Chocolate with Pistachio",
  "Ülker Kakaolu Bisküvi": "Ülker Cocoa Biscuits",
  "Ülker Probis Sandviç Bisküvi 10'lu 280G": "Ülker Probis Sandwich Biscuits 10-pack 280 g",
  "Uludağ limonata 1 lt şekersiz": "Uludağ Lemonade Sugar-Free 1 L",
  "Urfa kebap": "Urfa Kebab",
  "Vişne": "Sour Cherry",
  "Vitalis knusper muesli plus Honig-Mandel": "Vitalis Crunchy Muesli Honey & Almond",
  "Vitaminli Bisküviler": "Vitamin Biscuits",
  "Whey protein tozu": "Whey Protein Powder",
  "Whopper": "Whopper",
  "Yaban mersini": "Blueberries",
  "Yağlı Ayran": "Full-Fat Ayran (Yogurt Drink)",
  "Yağsız kıyma (%5)": "Lean Ground Meat (5% Fat)",
  "Yaprak sarma (etli)": "Stuffed Grape Leaves with Meat",
  "Yarım Yağlı Süt": "Semi-Skimmed Milk",
  "Yasemin pirinç (çiğ)": "Jasmine Rice (Raw)",
  "Yayla çorbası": "Yayla Soup (Yogurt & Rice Soup)",
  "Yer Fıstıklı Bar": "Peanut Bar",
  "Yeşil çay (şekersiz)": "Green Tea (Unsweetened)",
  "Yeşil mercimek (çiğ)": "Green Lentils (Raw)",
  "Yeşil mercimek (haşlanmış)": "Green Lentils (Boiled)",
  "Yeşil Mercimekli Bulgur Pilavı": "Bulgur Pilaf with Green Lentils",
  "Yoğurt": "Yogurt",
  "Yoğurt ve Mevsim Yeşillikli Patates Cipsi": "Yogurt & Herb Potato Chips",
  "Yulaf Kepeği": "Oat Bran",
  "Yulaf unu": "Oat Flour",
  "Yumurta (çiğ)": "Egg (Raw)",
  "Yumurta beyazı": "Egg White",
  "Yumurta sarısı": "Egg Yolk",
  "Yupo Jöle": "Yupo Jelly",
  "Zeytin ve Kekikli Kraker": "Olive & Oregano Crackers",
  "Zeytinyağı": "Olive Oil",
  "Zeytinyağlı enginar": "Artichokes in Olive Oil",
  "Zeytinyağlı pırasa": "Leeks in Olive Oil",
  "Zeytinyağlı taze fasulye": "Green Beans in Olive Oil",
  "Zeytinyağlı Ton Balığı": "Tuna in Olive Oil",

  "Aşure": "Aşure (Noah's Pudding)",
  "Bazlama": "Bazlama (Turkish Flatbread)",
  "Cikolatali gofret": "Chocolate Wafer",
  "Coca-Cola": "Coca-Cola",
  "Doğal Probiyotik Ananas": "Activia Probiotic Pineapple",
  "Eti Burçak Sütlü Çikolatalı": "Eti Burçak Milk Chocolate Biscuits",
  "eti canga": "Eti Canga Chocolate Bar",
  "Eti Karam Gurme": "Eti Karam Gourmet Dark Chocolate",
  "Eti Lifalif yulaf ezmesi 500": "Eti Lifalif Rolled Oats 500 g",
  "Eti Maximus": "Eti Maximus Chocolate Bar",
  "Eti Popkek Limonlu": "Eti Popkek Lemon Cake",
  "Fanta Portakal": "Fanta Orange",
  "Fit Yaşam Hindi Füme Eti": "Smoked Turkey Breast",
  "Godiva Masterpieces Bitter Çikolata Tablet": "Godiva Masterpieces Dark Chocolate Tablet",
  "İçim fit süt 500 laktozsuz vanilyalı": "İçim Fit Lactose-Free Vanilla Milk 500 ml",
  "Kazandibi": "Kazandibi (Caramelized Milk Pudding)",
  "Kırmızı Meyveli Tam Buğday Ve Pirinç Gevreği": "Whole Wheat & Rice Cereal with Red Berries",
  "Leblebi": "Leblebi (Roasted Chickpeas)",
  "Pastırma": "Pastırma (Cured Beef)",
  "Protein Bar Çikolata Hindistan Cevizi": "Protein Bar Chocolate & Coconut",
  "Ruffles 107gr": "Ruffles Original Potato Chips 107 g",
  "Simit": "Simit (Turkish Sesame Bagel)",
  "Sirma kaynak suyu": "Sırma Spring Water",
  "Sosis": "Sausage (Frankfurter)",
  "Sucuk": "Sujuk (Turkish Fermented Sausage)",
  "Süsse Finger bisküvi": "Süsse Finger Biscuits",
  "Şalgam suyu": "Şalgam (Fermented Turnip Juice)",
  "Tadım Fındıklı Bar": "Tadım Hazelnut Bar",
  "Ülker Bütün Antep Fıstıklı Sütlü Kare Çikolata": "Ülker Milk Chocolate Squares with Whole Pistachio",
  "Yarım Yağlı Yoğurt": "Semi-Skimmed Yogurt"
}$json$::jsonb)
) m
where public.tr_fold(f.name_tr) = public.tr_fold(m.tr);

-- Arama artık İngilizce adı da kapsıyor: "lentil soup" yazınca "Mercimek
-- çorbası" bulunur, Türkçe arama aynen çalışmaya devam eder.
create or replace function public.search_foods(p_query text)
returns setof public.foods
language plpgsql
stable
as $function$
declare
  q text := regexp_replace(public.tr_fold(btrim(coalesce(p_query, ''))), '\s+', ' ', 'g');
  toks text[];
begin
  select array_agg(t2)
    into toks
  from (
    select regexp_replace(t, '[^a-z0-9]', '', 'g') as t2
    from unnest(string_to_array(q, ' ')) t
  ) x
  where length(t2) >= 2;

  if toks is null then
    return;
  end if;

  return query
  select f.*
  from public.foods f
  cross join lateral (
    select btrim(public.tr_fold(f.name_tr || ' ' || coalesce(f.name_en, '') || ' ' || coalesce(f.brand, ''))) as n
  ) nn
  cross join lateral (
    select array_remove(regexp_split_to_array(nn.n, '[^a-z0-9]+'), '') as words
  ) ww
  where not exists (
    select 1
    from unnest(toks) t
    where not exists (
      select 1 from unnest(ww.words) w where w = t or w like t || '%'
    )
  )
  order by
    (btrim(public.tr_fold(f.name_tr)) = q
      or btrim(public.tr_fold(coalesce(f.name_en, ''))) = q) desc,          -- birebir ürün adı (TR ya da EN)
    (select count(*) from unnest(toks) t where t = any (ww.words)) desc,    -- tam kelime eşleşmesi
    (f.created_by = auth.uid()) desc nulls last,                            -- kendi yemeklerin
    (
      select min(ord)
      from unnest(ww.words) with ordinality u (w, ord)
      where w = toks[1] or w like toks[1] || '%'
    ) asc nulls last,                                                        -- eşleşme ne kadar önde
    f.is_verified desc,
    length(f.name_tr) asc,
    f.name_tr asc
  limit 30;
end;
$function$;
